# Site settings
title: "SR Consulting | Consultoria Salesforce | Implantação e Desenvolvimento"
description: "Consultoria parceira Salesforce, certificada em implantação, desenvolvimento e treinamento." # this means to ignore newlines until "baseurl:"
keyword: "Salesforce, Transformação Digital, Open Banking, Integração, B2B, B2C, Sales Clould, Service Cloud, Marketing Cloud, Social Studio, Commerce Cloud, Partner Community Cloud, Customer Community Clould, Financial Service Cloud, Helth Clould, Education Cloud, Einstein, Analytics, Tableau, Mulesoft, Heroku e App Exchange"
author: "SR Consulting Ltda"
email: "contato@srconsulting.io"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sr-consulting.github.io" # the base hostname & protocol for your site

phone_number: "+5551993263323"
phone_text: "+55 (51) 99326-3323"

whatsapp_number: "5551993263323"
whatsapp_text: "+55 (51) 99326-3323"

linkedin_username: "sr-consulting-ltda"
linkedin_text: "SR Consulting Ltda"

instagram_profile: "srconsulting.io"
instagram_text: "SR Consulting Ltda"

youtube_channel: "@DesbloqueandooSalesforce"
youtube_text: "Podcast: Desbloqueando o Salesforce"

address_line_1: "Tv. São José, 455 - 2º Andar - Navegantes"
address_line_2: "Porto Alegre - RS, CEP: 90240-200"

google_maps_embedded_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3455.409021858358!2d-51.20349164933422!3d-29.99640968181093!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x951979e0c5d78685%3A0x48abb378377374b3!2sInstituto%20Caldeira!5e0!3m2!1spt-BR!2sbr!4v1678839863665!5m2!1spt-BR!2sbr"
google_maps_link_url: https://goo.gl/maps/jBPMcnB8B7ExPnb9A

carrers_email: "carreiras@srconsulting.io"

appexchange_link_url: "https://appexchange.salesforce.com/appxConsultingListingDetail?listingId=a0N3u00000PH94dEAD"

gptw_link_url: "https://connect.gptw.info/certified-company?s=e24f2d58-f9c3-4489-aae1-2d5230f4abcf"

# Build settings
markdown: kramdown
