# Site settings
title: "SR Consulting | Consultoria Salesforce | Implantação e Desenvolvimento"
description: "Consultoria parceira Salesforce, certificada em implantação, desenvolvimento e treinamento." # this means to ignore newlines until "baseurl:"
keyword: "Salesforce, Transformação Digital, Open Banking, Integração, B2B, B2C, Sales Clould, Service Cloud, Marketing Cloud, Social Studio, Commerce Cloud, Partner Community Cloud, Customer Community Clould, Financial Service Cloud, Helth Clould, Education Cloud, Einstein, Analytics, Tableau, Mulesoft, Heroku e App Exchange"
author: "SR Consulting Ltda"
email: "contato@srconsulting.io"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sr-consulting.github.io" # the base hostname & protocol for your site

phone_number: "+555133781047"
phone_text: "+55 (51) 3378-1047"

whatsapp_number: "+5551996017922"
whatsapp_text: "+55 (51) 99601-7922"

linkedin_username: "sr-consulting-ltda"
linkedin_text: "SR Consulting Ltda"

address_line_1: "Av. Carlos Gomes, 222, 8º andar"
address_line_2: "Porto Alegre - RS, CEP: 90480-000"

google_maps_embedded_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3454.4555502067674!2d-51.18503438529988!3d-30.023785981889844!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x951979d4e9a5b78f%3A0xf1a6e3322ebfec8f!2sAv.%20Carlos%20Gomes%2C%20222%20-%20Boa%20Vista%2C%20Porto%20Alegre%20-%20RS%2C%2090480-000!5e0!3m2!1spt-BR!2sbr!4v1616977968028!5m2!1spt-BR!2sbr"
google_maps_link_url: https://goo.gl/maps/m3P2nPFsqW6DnMuV7

carrers_email: "carreiras@srconsulting.io"

appexchange_link_url: "https://appexchange.salesforce.com/appxConsultingListingDetail?listingId=a0N3u00000PH94dEAD"

# Build settings
markdown: kramdown
